### ISSUE TITLE
Move CLOSE button

### ISSUE THREAD

**Issue by SmartShots** [turbopasi/vu-welcome-screen#7]
I would like to see the CLOSE button moved to below the bottom left corner of the message box. Where it is right now it appears over the middle of the 'Deploy as' section, which shows behind it. At first glance it can make the 'CLOSE' button quite hard to notice. I think people would notice it better if it were under the message box, bottom left corner, as there is no underlying UI there.

**Comment by SmartShots** [comment]
I just realised another reason to move it. Mouse clicks still affect the underlying UI, so when I click on the 'CLOSE' button where it is currently it also tends to switch my current kit without me noticing. I have been trying to figure out why my kit kept getting switched to support or recon without me knowing. :-D

**Comment by turbopasi** [comment]
Yes I will definitely move it to account for the vanilla Battlefield 3 UI ! 👍
