### ISSUE TITLE
Add blur to background with options

### ISSUE THREAD

**Issue by SmartShots** [turbopasi/vu-welcome-screen#8]
It would be great to see a blur option added for the overlay background, along with a config setting for the amount of blur.

This would help to further separate the welcome screen UI from the game UI that is underlying it.

**Comment by turbopasi** [comment]
I need to check this - I don't think it's possible to blur everything except the WebUI - but definitely would be nice to have !

**Comment by SmartShots** [comment]
I haven't looked into coding for VU mods yet myself, so I don't know how the coding is put together. I know for websites you can use CSS to blur the background of a DIV.

https://www.w3schools.com/howto/howto_css_blurred_background.asp

**Comment by turbopasi** [comment]
I know about the filters, that's not the issue, but I think these web filters and blur effects would only affect content of the WebUI itself, not underlying game content - but haven't tried it so it would be worth a shot 👍
